[build]
  base      = "."
  command   = "npm run build --workspace=client"
  publish   = "client/dist"
  functions = "netlify/functions"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
